// Expanded skill list for diversity in matching
export const skills = [
  { skillId: 1, skillName: "🐍 Python" },
  { skillId: 2, skillName: "🌐 HTML" },
  { skillId: 3, skillName: "🎨 CSS" },
  { skillId: 4, skillName: "⚙️ JavaScript" },
  { skillId: 5, skillName: "🔷 TypeScript" },
  { skillId: 6, skillName: "⚛️ React" },
  { skillId: 7, skillName: "🌳 Node.js" },
  { skillId: 8, skillName: "🚀 Next.js" },
  { skillId: 9, skillName: "🛠️ Redux" },
  { skillId: 10, skillName: "🍃 MongoDB" },
  { skillId: 11, skillName: "🗄️ SQL" },
  { skillId: 12, skillName: "🔥 Firebase" },
  { skillId: 13, skillName: "🐟 Supabase" },
  { skillId: 14, skillName: "🌱 Git" },
  { skillId: 15, skillName: "🐳 Docker" },
  { skillId: 16, skillName: "☸️ Kubernetes" },
  { skillId: 17, skillName: "☁️ AWS" },
  { skillId: 18, skillName: "🔷 Azure" },
  { skillId: 19, skillName: "🔗 GraphQL" },
  { skillId: 20, skillName: "🌐 REST APIs" },
  { skillId: 21, skillName: "☕ Java" },
  { skillId: 22, skillName: "💻 C++" },
  { skillId: 23, skillName: "🦀 Rust" },
  { skillId: 24, skillName: "🐍 Django" },
  { skillId: 25, skillName: "🧪 Flask" },
  { skillId: 26, skillName: "📱 Swift" },
  { skillId: 27, skillName: "🚀 DevOps" },
  { skillId: 28, skillName: "🧠 Machine Learning" },
  { skillId: 29, skillName: "📊 Data Science" },
  { skillId: 30, skillName: "🌐 Cybersecurity" },
];

// Expanded user list with additional attributes and edge cases
export const users = [
  {
    id: 1,
    name: "Tony Stank",
    title: "3rd year SWE @ U of C",
    profilePic:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=2787&auto=format&fit=crop",
    skills: [0, 3, 5],
    role: "mentor",
    bio: "Passionate about helping others learn Python and React.",
    volunteerHours: 10.5,
  },
  {
    id: 2,
    name: "Bruce Banner",
    title: "Data Scientist @ Gamma Labs",
    profilePic:
      "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?q=80&w=2787&auto=format&fit=crop",
    skills: [28, 29],
    role: "both",
    bio: "Researching ML with a focus on gamma radiation.",
    volunteerHours: 20.0,
  },
  {
    id: 3,
    name: "Natasha Romanoff",
    title: "Security Analyst @ SHIELD",
    profilePic:
      "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?q=80&w=2787&auto=format&fit=crop",
    skills: [30, 3],
    role: "mentor",
    bio: "Experience in cybersecurity for high-stakes operations.",
    volunteerHours: 5.2,
  },
  {
    id: 4,
    name: "Steve Rogers",
    title: "Backend Developer @ Stark Industries",
    profilePic:
      "https://images.unsplash.com/photo-1511367461989-f85a21fda167?q=80&w=2787&auto=format&fit=crop",
    skills: [0, 11, 10],
    role: "learner",
    bio: "Learning SQL and backend development to support tech initiatives.",
    volunteerHours: 2.0,
  },
  {
    id: 5,
    name: "Peter Parker",
    title: "Junior Dev @ Daily Bugle",
    profilePic:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=2787&auto=format&fit=crop",
    skills: [1, 3, 5],
    role: "learner",
    bio: "High school intern learning web dev.",
    volunteerHours: 0.0,
  },
  {
    id: 6,
    name: "Pepper Potts",
    title: "Project Manager @ Stark Enterprises",
    profilePic:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=2787&auto=format&fit=crop",
    skills: [2, 27, 17],
    role: "both",
    bio: "Managing complex projects with DevOps skills.",
    volunteerHours: 12.3,
  },
  {
    id: 7,
    name: "Shuri",
    title: "Machine Learning Engineer @ Wakanda Labs",
    profilePic:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=2787&auto=format&fit=crop",
    skills: [28, 6, 7],
    role: "mentor",
    bio: "Working on ML models and AI tools.",
    volunteerHours: 25.0,
  },
  {
    id: 8,
    name: "Scott Lang",
    title: "DevOps Engineer @ Quantum Tech",
    profilePic:
      "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=2787&auto=format&fit=crop",
    skills: [15, 16, 27],
    role: "both",
    bio: "Passionate about optimizing workflows and deploying code.",
    volunteerHours: 14.7,
  },
  {
    id: 9,
    name: "Carol Danvers",
    title: "Cloud Architect @ SpaceForce",
    profilePic:
      "https://images.unsplash.com/photo-1549237519-e6d2b1dacc90?q=80&w=2787&auto=format&fit=crop",
    skills: [17, 18, 30],
    role: "mentor",
    bio: "Architecting secure and scalable cloud solutions.",
    volunteerHours: 18.0,
  },
  {
    id: 10,
    name: "Wanda Maximoff",
    title: "Full Stack Developer @ VisionWorks",
    profilePic:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=2787&auto=format&fit=crop",
    skills: [0, 3, 8],
    role: "learner",
    bio: "Exploring the connections between frontend and backend development.",
    volunteerHours: 6.5,
  },
  {
    id: 11,
    name: "Vision",
    title: "AI Specialist @ Vibranium Labs",
    profilePic:
      "https://images.unsplash.com/photo-1517365830460-955ce3ccd263?q=80&w=2787&auto=format&fit=crop",
    skills: [28, 19, 20],
    role: "mentor",
    bio: "Focused on predictive AI and data modeling.",
    volunteerHours: 19.2,
  },
  {
    id: 12,
    name: "Stephen Strange",
    title: "Senior Software Engineer @ Mystic Arts",
    profilePic:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=2787&auto=format&fit=crop",
    skills: [21, 22, 5],
    role: "both",
    bio: "Exploring software engineering in parallel universes.",
    volunteerHours: 11.5,
  },
  {
    id: 13,
    name: "Drax",
    title: "Network Engineer @ Planetary Networks",
    profilePic:
      "https://images.unsplash.com/photo-1549237519-e6d2b1dacc90?q=80&w=2787&auto=format&fit=crop",
    skills: [15, 7, 10],
    role: "learner",
    bio: "Ensuring connectivity across galactic systems.",
    volunteerHours: 4.0,
  },
  {
    id: 14,
    name: "Gamora",
    title: "Security Engineer @ Intergalactic Security",
    profilePic:
      "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?q=80&w=2787&auto=format&fit=crop",
    skills: [30, 5, 18],
    role: "mentor",
    bio: "Expert in securing intergalactic networks and sensitive data.",
    volunteerHours: 7.5,
  },
  {
    id: 15,
    name: "Bucky Barnes",
    title: "Cybersecurity Engineer @ Winter Tech",
    profilePic:
      "https://images.unsplash.com/photo-1511367461989-f85a21fda167?q=80&w=2787&auto=format&fit=crop",
    skills: [4, 11, 30],
    role: "both",
    bio: "Combining cybersecurity expertise with a passion for secure coding.",
    volunteerHours: 8.2,
  },
  {
    id: 16,
    name: "T'Challa",
    title: "Product Designer @ Wakanda Innovations",
    profilePic:
      "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?q=80&w=2787&auto=format&fit=crop",
    skills: [2, 4, 24],
    role: "learner",
    bio: "Designing intuitive products with a focus on user experience.",
    volunteerHours: 12.3,
  },
  {
    id: 17,
    name: "Shuri",
    title: "Machine Learning Engineer @ Wakanda Labs",
    profilePic:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=2787&auto=format&fit=crop",
    skills: [skills[28], skills[6], skills[7]],
    role: "mentor",
    bio: "Pushing the boundaries of machine learning with cutting-edge technologies.",
    volunteerHours: 16.7,
  },
  {
    id: 18,
    name: "Clint Barton",
    title: "Frontend Developer @ Avengy Solutions",
    profilePic:
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=2787&auto=format&fit=crop",
    skills: [4, 1, 5],
    role: "both",
    bio: "Creating seamless and interactive web experiences.",
    volunteerHours: 5.8,
  },
  {
    id: 19,
    name: "Peter Quill",
    title: "Product Manager @ Starfleet Industries",
    profilePic:
      "https://images.unsplash.com/photo-1517365830460-955ce3ccd263?q=80&w=2787&auto=format&fit=crop",
    skills: [7, 17, 12],
    role: "learner",
    bio: "Managing product development and strategy for a new tech company.",
    volunteerHours: 0.5,
  },
  {
    id: 20,
    name: "Rocket Raccoon",
    title: "Robotics Engineer @ Guardians Engineering",
    profilePic:
      "https://images.unsplash.com/photo-1517365830460-955ce3ccd263?q=80&w=2787&auto=format&fit=crop",
    skills: [21, 15, 27],
    role: "mentor",
    bio: "Building the next generation of autonomous robots.",
    volunteerHours: 20.5,
  },
  {
    id: 21,
    name: "Loki",
    title: "Full Stack Developer @ Trickster Solutions",
    profilePic:
      "https://images.unsplash.com/photo-1517365830460-955ce3ccd263?q=80&w=2787&auto=format&fit=crop",
    skills: [5, 14, 11],
    role: "both",
    bio: "Master of both frontend and backend technologies.",
    volunteerHours: 9.0,
  },
  {
    id: 22,
    name: "Thor",
    title: "DevOps Engineer @ Asgard Technologies",
    profilePic:
      "https://images.unsplash.com/photo-1517365830460-955ce3ccd263?q=80&w=2787&auto=format&fit=crop",
    skills: [16, 18, 27],
    role: "learner",
    bio: "Improving deployment processes with automation and cloud technologies.",
    volunteerHours: 13.0,
  },
  {
    id: 23,
    name: "Gamora",
    title: "Security Engineer @ Intergalactic Security",
    profilePic:
      "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?q=80&w=2787&auto=format&fit=crop",
    skills: [30, 5, 18],
    role: "mentor",
    bio: "Expert in securing intergalactic networks and sensitive data.",
    volunteerHours: 7.5,
  },
  {
    id: 24,
    name: "Nebula",
    title: "Backend Developer @ Infinity Code",
    profilePic:
      "https://images.unsplash.com/photo-1517365830460-955ce3ccd263?q=80&w=2787&auto=format&fit=crop",
    skills: [9, 7, 0],
    role: "mentor",
    bio: "Writing high-performance backend services and APIs.",
    volunteerHours: 10.0,
  },
  {
    id: 25,
    name: "Mantis",
    title: "UX Designer @ Guardians of Tech",
    profilePic:
      "https://images.unsplash.com/photo-1517365830460-955ce3ccd263?q=80&w=2787&auto=format&fit=crop",
    skills: [2, 6, 12],
    role: "learner",
    bio: "Designing user-friendly and beautiful interfaces for tech products.",
    volunteerHours: 4.5,
  },
  {
    id: 26,
    name: "Star-Lord",
    title: "Product Designer @ Galactic Ventures",
    profilePic:
      "https://images.unsplash.com/photo-1517365830460-955ce3ccd263?q=80&w=2787&auto=format&fit=crop",
    skills: [2, 8, 17],
    role: "both",
    bio: "Balancing design with product management for high-impact projects.",
    volunteerHours: 6.0,
  },
  {
    id: 27,
    name: "Hawkeye",
    title: "Cybersecurity Engineer @ Hawkeye Security",
    profilePic:
      "https://images.unsplash.com/photo-1517365830460-955ce3ccd263?q=80&w=2787&auto=format&fit=crop",
    skills: [5, 30, 20],
    role: "mentor",
    bio: "Securing networks with a precision-guided approach.",
    volunteerHours: 8.0,
  },
  {
    id: 28,
    name: "Black Widow",
    title: "Software Engineer @ Widow Technologies",
    profilePic:
      "https://images.unsplash.com/photo-1517365830460-955ce3ccd263?q=80&w=2787&auto=format&fit=crop",
    skills: [4, 1, 5],
    role: "learner",
    bio: "Learning full-stack development with a focus on security.",
    volunteerHours: 2.5,
  },
  {
    id: 29,
    name: "Hulk",
    title: "Big Data Engineer @ Gamma Data",
    profilePic:
      "https://images.unsplash.com/photo-1517365830460-955ce3ccd263?q=80&w=2787&auto=format&fit=crop",
    skills: [28, 19, 9],
    role: "mentor",
    bio: "Processing and managing massive datasets with machine learning.",
    volunteerHours: 18.3,
  },
  {
    id: 30,
    name: "Doctor Strange",
    title: "Quantum Computing Specialist @ Strange Labs",
    profilePic:
      "https://images.unsplash.com/photo-1517365830460-955ce3ccd263?q=80&w=2787&auto=format&fit=crop",
    skills: [16, 14, 20],
    role: "mentor",
    bio: "Working on quantum algorithms and exploring the future of computing.",
    volunteerHours: 22.0,
  },
];
